# Gradle memory limit set to prevent OOM on GitHub Runners
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m

# Enable parallel and caching features for faster & lighter builds
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

android.suppressUnsupportedCompileSdk=35
android.useAndroidX=true
android.nonTransitiveRClass=true